/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppNavBar: typeof import('./src/components/AppNavBar.vue')['default']
    BreadCrumbs: typeof import('./src/components/BreadCrumbs.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    EditorTest: typeof import('./src/components/EditorTest.vue')['default']
    ListOfCreatedManuscripts: typeof import('./src/components/ListOfCreatedManuscripts.vue')['default']
    ListOfExtractedManuscripts: typeof import('./src/components/ListOfExtractedManuscripts.vue')['default']
    ManuscriptArea: typeof import('./src/components/ManuscriptArea.vue')['default']
    ManuscriptContent: typeof import('./src/components/ManuscriptContent.vue')['default']
    ManuscriptData: typeof import('./src/components/ManuscriptData.vue')['default']
    NotificationComponent: typeof import('./src/components/NotificationComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
