/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/annotate': RouteRecordInfo<'/annotate', '/annotate', Record<never, never>, Record<never, never>>,
    '/AutoClassifyView': RouteRecordInfo<'/AutoClassifyView', '/AutoClassifyView', Record<never, never>, Record<never, never>>,
    '/ConvertLODView': RouteRecordInfo<'/ConvertLODView', '/ConvertLODView', Record<never, never>, Record<never, never>>,
    '/download': RouteRecordInfo<'/download', '/download', Record<never, never>, Record<never, never>>,
    '/FeedbackView': RouteRecordInfo<'/FeedbackView', '/FeedbackView', Record<never, never>, Record<never, never>>,
    '/FileUploadView': RouteRecordInfo<'/FileUploadView', '/FileUploadView', Record<never, never>, Record<never, never>>,
    '/InspectionView': RouteRecordInfo<'/InspectionView', '/InspectionView', Record<never, never>, Record<never, never>>,
    '/LandingView': RouteRecordInfo<'/LandingView', '/LandingView', Record<never, never>, Record<never, never>>,
    '/Locus': RouteRecordInfo<'/Locus', '/Locus', Record<never, never>, Record<never, never>>,
    '/ManuscriptDescriptionChoice': RouteRecordInfo<'/ManuscriptDescriptionChoice', '/ManuscriptDescriptionChoice', Record<never, never>, Record<never, never>>,
    '/MappingConcepts': RouteRecordInfo<'/MappingConcepts', '/MappingConcepts', Record<never, never>, Record<never, never>>,
    '/MappingConceptsView': RouteRecordInfo<'/MappingConceptsView', '/MappingConceptsView', Record<never, never>, Record<never, never>>,
    '/mention_information': RouteRecordInfo<'/mention_information', '/mention_information', Record<never, never>, Record<never, never>>,
    '/NextPage': RouteRecordInfo<'/NextPage', '/NextPage', Record<never, never>, Record<never, never>>,
    '/PhysicalCharacteristics': RouteRecordInfo<'/PhysicalCharacteristics', '/PhysicalCharacteristics', Record<never, never>, Record<never, never>>,
    '/RdfPage': RouteRecordInfo<'/RdfPage', '/RdfPage', Record<never, never>, Record<never, never>>,
    '/resultsView': RouteRecordInfo<'/resultsView', '/resultsView', Record<never, never>, Record<never, never>>,
    '/source': RouteRecordInfo<'/source', '/source', Record<never, never>, Record<never, never>>,
    '/StructureView': RouteRecordInfo<'/StructureView', '/StructureView', Record<never, never>, Record<never, never>>,
  }
}
